# Generated by Django 2.2.2 on 2019-12-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fundaciones',
            new_name='Fundacion',
        ),
    ]
