# Generated by Django 2.2.2 on 2019-12-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191211_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacion',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
