# Generated by Django 2.2.2 on 2019-12-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_auto_20191218_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('Adulto', 'Adulto'), ('Cachorro', 'Cachorro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fundacion',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='personalidad',
            field=models.CharField(choices=[('Timido', 'Timido'), ('Tranquilo', 'Tranquilo'), ('Dormilon', 'Dormilon'), ('Jugueton', 'Jugueton'), ('Mañoso', 'Mañoso')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamano',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('Gato', 'Gato'), ('Perro', 'Perro')], max_length=10),
        ),
    ]
