# Generated by Django 2.2.2 on 2019-12-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20191220_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='mail_fundacion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
